import 'package:flutter/material.dart';

const Map<String, String> requests = {
  'trending': 'https://api.themoviedb.org/3/trending/%s/%s?language=en-US&api_key=e2c7d1908816457a2156268c1fb5d7ae&page=%s',
  'providers': 'https://api.themoviedb.org/3/%s/%s/watch/providers?include_adult=true&language=en-US&api_key=e2c7d1908816457a2156268c1fb5d7ae',
  'image': 'https://image.tmdb.org/t/p/w500%s',
};

const List<DropdownMenuItem<String>> movieGenreItems = [
  DropdownMenuItem(value: '0', child: Text( 'None' )),
  DropdownMenuItem(value: '28', child: Text( 'Action' )),
  DropdownMenuItem(value: '12', child: Text( 'Adventure' )),
  DropdownMenuItem(value: '16', child: Text( 'Animation' )),
  DropdownMenuItem(value: '35', child: Text( 'Comedy' )),
  DropdownMenuItem(value: '80', child: Text( 'Crime' )),
  DropdownMenuItem(value: '99', child: Text( 'Documentary' )),
  DropdownMenuItem(value: '18', child: Text( 'Drama' )),
  DropdownMenuItem(value: '10751', child: Text( 'Family' )),
  DropdownMenuItem(value: '14', child: Text( 'Fantasy' )),
  DropdownMenuItem(value: '36', child: Text( 'History' )),
  DropdownMenuItem(value: '27', child: Text( 'Horror' )),
  DropdownMenuItem(value: '10402', child: Text( 'Music' )),
  DropdownMenuItem(value: '9648', child: Text( 'Mystery' )),
  DropdownMenuItem(value: '10749', child: Text( 'Romance' )),
  DropdownMenuItem(value: '878', child: Text( 'Science Fiction' )),
  DropdownMenuItem(value: '10770', child: Text( 'TV Movie' )),
  DropdownMenuItem(value: '53', child: Text( 'Thriller' )),
  DropdownMenuItem(value: '10752', child: Text( 'War' )),
  DropdownMenuItem(value: '37', child: Text( 'Western' ))
];

const List<DropdownMenuItem<String>> tvGenreItems = [
  DropdownMenuItem(value: '0', child: Text( 'None' )),
  DropdownMenuItem(value: '10759', child: Text( 'Action & Adventure' )),
  DropdownMenuItem(value: '16', child: Text( 'Animation' )),
  DropdownMenuItem(value: '35', child: Text( 'Comedy' )),
  DropdownMenuItem(value: '80', child: Text( 'Crime' )),
  DropdownMenuItem(value: '99', child: Text( 'Documentary' )),
  DropdownMenuItem(value: '18', child: Text( 'Drama' )),
  DropdownMenuItem(value: '10751', child: Text( 'Family' )),
  DropdownMenuItem(value: '10762', child: Text( 'Kids' )),
  DropdownMenuItem(value: '9648', child: Text( 'Mystery' )),
  DropdownMenuItem(value: '10763', child: Text( 'News' )),
  DropdownMenuItem(value: '10764', child: Text( 'Reality' )),
  DropdownMenuItem(value: '10765', child: Text( 'Sci-Fi & Fantasy' )),
  DropdownMenuItem(value: '10766', child: Text( 'Soap' )),
  DropdownMenuItem(value: '10767', child: Text( 'Talk' )),
  DropdownMenuItem(value: '10768', child: Text( 'War & Politics' )),
  DropdownMenuItem(value: '37', child: Text( 'Western' )),
];

const List<DropdownMenuItem<String>> contentTypeItems = [
  DropdownMenuItem(value: 'movie', child: Text('Movie')),
  DropdownMenuItem(value: 'tv', child: Text('TV')),
];

const List<DropdownMenuItem<String>> timePeriodItems = [
  DropdownMenuItem(value: 'day', child: Text('Day')),
  DropdownMenuItem(value: 'week', child: Text('Week')),
];

const List<String> countryList =  [
  'US',
  'CN',
  'JP',
  'DE',
  'IN',
  'GB',
  'FR',
  'RU',
  'CA',
  'IT',
  'BR',
  'AU',
  'KR',
  'MX',
  'ES',
  'ID',
  'SA',
  'NL',
  'TR',
  'CH',
  'TW',
  'PL',
  'AR',
  'SE',
  'BE',
  'NO',
  'TH',
  'IE',
  'IL',
  'AE',
  'NG',
  'EG',
  'AT',
  'SG',
  'BD',
  'MY',
  'VN',
  'ZA',
  'PH',
  'DK',
  'HK',
  'IR',
  'CO',
  'RO',
  'CL',
  'CZ',
  'FI',
  'IQ',
  'PT',
  'PE',
  'NZ',
  'KZ',
  'QA',
  'GR',
  'DZ',
  'KW',
  'HU',
  'UA',
  'MA',
  'AO',
  'ET',
  'PR',
  'EC',
  'KE',
  'OM',
  'SK',
  'DO',
  'GT',
  'VE',
  'BG',
  'LU',
  'UZ',
  'TM',
  'TZ',
  'BY',
  'GH',
  'PA',
  'UY',
  'HR',
  'RS',
  'LT',
  'CI',
  'AZ',
  'CR',
  'CD',
  'SI',
  'MM',
  'SD',
  'UG',
  'JO',
  'TN',
  'BH',
  'LY',
  'CM',
  'BO',
  'LV',
  'PY',
  'NP',
  'EE',
  'ZW',
  'PG',
  'SV',
  'HN',
  'KH',
  'ZM',
  'CY',
  'TT',
  'IS',
  'SN',
  'BA',
  'GE',
  'MO',
  'GA',
  'YE',
  'HT',
  'GN',
  'BF',
  'AM',
  'BW',
  'ML',
  'PS',
  'AL',
  'MZ',
  'MT',
  'BJ',
  'MN',
  'BN',
  'GQ',
  'JM',
  'NI',
  'LA',
  'MG',
  'NE',
  'GY',
  'MD',
  'MK',
  'BS',
  'MU',
  'RW',
  'CG',
  'MW',
  'NA',
  'TD',
  'KG',
  'TJ',
  'MR',
  'XK',
  'TG',
  'SO',
  'SS',
  'MV',
  'ME',
  'BB',
  'FJ',
  'SZ',
  'LR',
  'SL',
  'BI',
  'TL',
  'DJ',
  'SR',
  'AW',
  'AD',
  'BZ',
  'BT',
  'LS',
  'CF',
  'ER',
  'CV',
  'GM',
  'LC',
  'SC',
  'GW',
  'SM',
  'AG',
  'SB',
  'KM',
  'GD',
  'VU',
  'KN',
  'VC',
  'WS',
  'DM',
  'ST',
  'TO',
  'FM',
  'MH',
  'PW',
  'KI',
  'NR',
  'TV'
];